class demo_Register_locator:
    create_account_button = "css selector,button[ng-click='createAccount()']"
    search_institution_box = "css selector,[id='searchInput']"
    next_button_after_institution_search = "css selector,[class='course-add-button gray-focus']"
    first_name_box = "id,firstName"
    last_name_box = "id,lastName"
    email_id_box = "id,email"
    reef_id_box = "id,studentId"
    policy_checkbox_button = "id,studentAgreement"
    next_button_after_details = "css selector,[class='course-add-button gray-focus']"
    sign_up_button = "css selector,[class='login-page-text-bold white-focus']"
    select_institution_name_given_list = "xpath,//span[text()='REEF Education']"
    password = "css selector,[id='password']"
    confirm_password = "css selector,[id='confirmPassword']"
    create_account_click01 = "css selector,[class='course-add-button gray-focus']"
    login_email_id="id,userEmail"
    user_password="id,userPassword"
    sign_in_button_for_login="id,sign-in-button"
